version: 2.1

orbs:
 node: circleci/node@4.0.0

executors:
 node:
  docker:
   - image: cimg/base:2020.01
   - image: circleci/mongo:latest

jobs:
 build:
  working_directory: ~/humantic
  executor: node
  steps:
   - checkout
   - node/install:
      install-yarn: true
      lts: true
   - node/install-yarn
   - run: node --version
   - run: yarn --version
   - node/install-packages:
      app-dir: ~/humantic
      pkg-manager: yarn
   - run: yarn build
 publish:
  working_directory: ~/humantic
  executor: node
  steps:
   - checkout
   - node/install:
      install-yarn: true
      lts: true
   - node/install-yarn
   - node/install-packages:
      app-dir: ~/humantic
      pkg-manager: yarn
      override-ci-command: yarn --frozen-lockfile
   - run:
      name: Authenticate with registry
      command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/humantic/.npmrc
   - run: yarn run lerna publish from-package -y

workflows:
 build_and_publish:
  jobs:
   - build
   - publish:
      requires:
       - build
