version: 2.1

# Required Environment Variables that are used by configuration:
# CODECOV_TOKEN (Project-based)
# CODACY_PROJECT_TOKEN (Project-based)
# NPM_TOKEN (Project-based, can be global)
# SKIP_PREFLIGHT_CHECK (true)... Damn CRA :/
#
# DOCKER_LOGIN
# DOCKER_PASSWORD

orbs:
  node: circleci/node@4.0.0
  docker: circleci/docker@1.4.0
  codecov: codecov/codecov@1.1.1
  codacy: codacy/coverage-reporter@11.2.1

executors:
  node:
    docker:
      - image: cimg/node:12.18.2
      - image: circleci/mongo:latest

# There we would like to have also matrix testing to automatically
# test our code on newest Node.js version isnstead LTS.

jobs:
  build:
    working_directory: ~/humantic
    executor: node
    steps:
      - checkout
      - node/install-yarn
      # Install packages from main directory (just in case)
      - node/install-packages:
          app-dir: ~/humantic
          pkg-manager: yarn
      # Install packages at API Directory
      - node/install-packages:
          app-dir: ~/humantic/services/api
          pkg-manager: yarn
      - run: cd ~/humantic/services/api
      - run: yarn build
      - run: yarn test:unit
      - run: yarn test:cov
      # Install packages at UI Directory
      - node/install-packages:
          app-dir: ~/humantic/services/ui
          pkg-manager: yarn
      - run: cd ~/humantic/services/ui
      - run: yarn build
      - run: cd ~/humantic
      - codecov/upload
      - codacy/send_report
