version: 2.1

# Required Environment Variables that are used by configuration:
# CODECOV_TOKEN (Project-based)
# CODACY_PROJECT_TOKEN (Project-based)
# NPM_TOKEN (Project-based, can be global)
# SKIP_PREFLIGHT_CHECK (true)... Damn CRA :/

orbs:
 node: circleci/node@4.0.0
 docker: circleci/docker@1.4.0
 codecov: codecov/codecov@1.1.1

executors:
 node:
  docker:
   - image: cimg/base:2020.01
   - image: circleci/mongo:latest

jobs:
 build:
  working_directory: ~/humantic
  executor: node
  steps:
   - checkout
   - node/install:
      install-yarn: true
      lts: true
   - node/install-yarn
   - run: node --version
   - run: yarn --version
   - node/install-packages:
      app-dir: ~/humantic
      pkg-manager: yarn
   - run: yarn build

 test_unit:
  working_directory: ~/humantic
  executor: node
  steps:
   - checkout
   - node/install:
      install-yarn: true
      lts: true
   - node/install-yarn
   - run: node --version
   - run: yarn --version
   - node/install-packages:
      app-dir: ~/humantic
      pkg-manager: yarn
   - run: yarn test:unit

 coverage:
  working_directory: ~/humantic
  executor: node
  steps:
   - checkout
   - node/install:
      install-yarn: true
      lts: true
   - node/install-packages:
      app-dir: ~/humantic
      pkg-manager: yarn
   - run: yarn test:cov
   - codecov/upload
   - run: bash <(curl -Ls https://coverage.codacy.com/get.sh)

 #  docker_build:
 #   working_directory: ~/humantic
 #   executor: docker/docker
 #   steps:
 #    - setup_remote_docker:
 #       docker_layer_caching: false
 #    - checkout
 #    - docker/check
 #    - docker/build

 # Publish packages contained in repository to NPM.
 # TODO: Packages should be stored on GitHub Packages instead NPM.
 publish:
  working_directory: ~/humantic
  executor: node
  steps:
   - checkout
   - node/install:
      install-yarn: true
      lts: true
   - node/install-yarn
   - node/install-packages:
      app-dir: ~/humantic
      pkg-manager: yarn
      override-ci-command: yarn --frozen-lockfile
   - run:
      name: Authenticate with registry
      command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/humantic/.npmrc
   - run: yarn run lerna publish from-package -y

workflows:
 build_and_publish:
  jobs:
   # TODO: We should think about optimalizing Node.js installation since
   # there is no sense for installing same Node.js version multiple times
   # to perform simple tasks.
   - build
   - test_unit:
      requires:
       - build
   - coverage:
      requires:
       - build
   # TODO: There we should implement Orb in better way with whole
   # lifecycle testing and artifact sharing with builded .tar from image.
   # https://circleci.com/orbs/registry/orb/circleci/docker
   # - docker/publish:
   #    image: humwrk/api
   #    path: ~/humantic/services/api
   #    dockerfile: .docker/Dockerfile
   #    registry: docker.io
