version: 2.1

orbs:
  node: circleci/node@4.0.0

executors:
  node:
    docker:
      - image: cimg/node:lts
      - image: 'circleci/mongo:latest'

jobs:
  test:
    working_directory: ~/humantic
    executor: node
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: lts
      - run: node --version
      - run: yarn --version
      - node/install-packages:
          app-dir: ~/humantic
          pkg-manager: yarn
      - run: yarn test

workflows:
  test:
    jobs:
      - test
