#%RAML 1.0
title: HumwrkSystem
version: v1
baseUri: 'http://api.humwrk.com'
description: General API Related to Humantic Project
types:
  Project:
    type: object
    properties:
      header: string
      description: string
      technology: array(string)
      reqiurements: array(string)
      assignedTo?: array(string)
      applicants?: array(string)
      isFixed: boolean
      budget?: number
      rate?: number
      deadline?: date-only
      state?: string
      milestones: array(string)

/projects:
    post:
      body:
        application/json:
          schema: Project
          type: Project
          isAnnotation: false
      responses:
        201:
          body:
            application/json:
              example:
                data:
                  header: "Node.js Developer"
    get:
      responses:
        '200':
          body:
            application/json:
              type: array(Project)
    /:id:
      get:
        responses:
          200:
            body:
              application/json:
                type: Project
          404:
            body:
              application/json:
                error: "Project was not found"
        queryParameters:
          id: string
        body:
          application/json:
            schema: Project
            type: Project
      patch:
      delete:
