# Developer-centered docker-compose file which introduces only basic services that are needed to run packages locally.

version: '3.8'

services:
  mongodb:
    container_name: humantic-mongodb
    image: mongo
    ports:
      - 27017:27017
